### ISSUE TITLE
products page not working properly on my PC

### ISSUE THREAD

**Issue by mystere3** [mystere3/businessWebsite#1]
Hey guys. I've seen my page working from 2 different mac's but I just tried it out on my PC and it doesn't work properly on either chrome or ie.

If you guys wouldn't mind opening my page on your machines at some point I'd appreciate it. Just choose things using the form and let me know if it looks like its providing the correct bikes back. On my pc no matter what choices I make, it provides the entirety of the "all bikes" array.

I haven't bothered digging in looking for a solution yet because I'm guessing it has something to do with the file path or something stupid on this machine. If it works on both of your machines I'm going to ignore it. Thanks.

**Comment by himanshuanand** [comment]
The page and search feature is working fine on my PC. Just tried it in
Chrome. I think you can ignore it.

I have updated the trails page to add google custom search.

On Fri, Feb 27, 2015 at 11:52 PM, mystere3 notifications@github.com wrote:

> Hey guys. I've seen my page working from 2 different mac's but I just
> tried it out on my PC and it doesn't work properly on either chrome or ie.
> 
> If you guys wouldn't mind opening my page on your machines at some point
> I'd appreciate it. Just choose things using the form and let me know if it
> looks like its providing the correct bikes back. On my pc no matter what
> choices I make, it provides the entirety of the "all bikes" array.
> 
> I haven't bothered digging in looking for a solution yet because I'm
> guessing it has something to do with the file path or something stupid on
> this machine. If it works on both of your machines I'm going to ignore it.
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mystere3/businessWebsite/issues/1.

## 

Himanshu Anand

**Comment by m00tzman** [comment]
Yeah, I just tried it on my Mac on Chrome and Safari and it worked perfectly fine.

**Comment by mystere3** [comment]
great thanks.

**Comment by mystere3** [comment]
I'm going to try to find time to create a contacts page if no one else has done one yet.
